name: Perpetual VDS with tmate

on:
  # Позволяет запускать вручную из интерфейса GitHub
  workflow_dispatch:

  # Позволяет воркеру запускать самого себя для перезапуска
  repository_dispatch:
    types: [restart-vds]

jobs:
  build:
    runs-on: ubuntu-latest
    # Таймаут 5 часов 55 минут, чтобы оставить 5 минут на бэкап и перезапуск
    timeout-minutes: 355

    steps:
      # Шаг 1: Скачиваем код репозитория
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 2: Восстанавливаем данные из бэкапа, если он существует
      - name: Restore Data from Backup
        run: |
          if [ -f "vds_backup.zip" ]; then
            echo "Backup file found. Restoring..."
            unzip -o vds_backup.zip -d ./
          else
            echo "No backup found. Starting fresh."
          fi

      # Шаг 3: Устанавливаем tmate и запускаем сессию в фоне
      - name: Setup and Run tmate
        id: tmate_session
        run: |
          sudo apt-get update && sudo apt-get install -y tmate

          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          TMATE_SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "TMATE_SSH_URL=${TMATE_SSH}" >> $GITHUB_OUTPUT
          echo "========================================================================="
          echo "SSH connection string: ${TMATE_SSH}"
          echo "========================================================================="

      # Шаг 4: Сохраняем SSH-ссылку в текстовый файл
      - name: Save SSH Link to File
        run: echo "${{ steps.tmate_session.outputs.TMATE_SSH_URL }}" > ssh_link.txt

      # Шаг 5: Ждем 5 часов 45 минут
      - name: Keep VDS Alive
        run: |
          echo "VDS is running. Will shut down and backup in approximately 5 hours 45 minutes."
          sleep 20700

      # Шаг 6: Создаем бэкап перед завершением
      - name: Create Backup
        run: |
          echo "Creating data backup..."
          zip -r vds_backup.zip . -x ".git/*" "vds_backup.zip" "ssh_link.txt"

      # Шаг 7: Коммитим бэкап и ssh-ссылку в репозиторий
      - name: Commit Backup and SSH Link
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "VDS Backup & SSH Link Auto-Update"
          file_pattern: "vds_backup.zip ssh_link.txt"

      # ✅ Шаг 8: Перезапуск следующей сессии через PAT
      - name: Trigger Next VDS Run
        run: |
          echo "Triggering VDS restart..."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.VDS_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "restart-vds"}'
